### ISSUE TITLE
There is no way to unbeastify a web page

### ISSUE THREAD

**Issue by kumar303** [mdn/webextensions-examples#106]
Steps to reproduce:
* Install the `beastify` extension
* Navigate to a web page
* Beastify the web page, such as selecting 'Frog'

In this state, there is no intuitive way to "unbeastify" the web page, i.e. return it to its original form. You can refresh the URL but that isn't exactly obvious.

I know this is just an example extension but showing some code to restore the original web page might also be a useful example for someone.

**Comment by nistath** [comment]
I'm on it! I will have to remove the removeEverything method though, and replace it with some sort of overlay.

**Comment by wbamberg** [comment]
Thanks @nistath ! I did wonder if you might also consider unbeastifying by just reloading the page. Just a suggestion though, feel free to try any approach that seems to work :).

**Comment by wbamberg** [comment]
Actually, one other thing about this issue: we use this example in an introductory walkthrough doc: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_second_WebExtension, and for that reason I'm keen to keep the example quite simple. So if the fix for this is simple, that's great, but if it adds a lot of extra complexity, it might not be such a good idea.

Is the idea something like this: that if you click the button,
* if the page has not been beastified, then the popup looks as it does now
* if the page has been beastified, then the popup contains an "unbeastify" button?

If so, the tricky bit seems to me to be knowing whether the page has been beastified or not, at the time you display the popup.

**Comment by nistath** [comment]
I've implemented 2 unbeastifying methods: one that removes everything and another that reloads.
I'll try to get them to show only if the page has been beastified.
I've also updated the documentation.
I'll PR as I work on it.

**Comment by nistath** [comment]
I'll add the unbeastify/clear buttons via the javascript.

**Comment by nistath** [comment]
I can't know whether or not the page has been beastified at the time the popup displays, without making the code more complicated than it needs to be for an introductory level.

I've written good documentation and I think this example has gotten as advanced as it should.

**Comment by nistath** [comment]
#109 is pretty final right now. Can we merge it?

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/webextensions-examples/pull/109.
