### ISSUE TITLE
bookmark-it bookmarks wrong tab

### ISSUE THREAD

**Issue by frostschutz** [mdn/webextensions-examples#182]
When using more than one browser window, clicking the bookmark-it icon in Window X, instead of bookmarking tab X, instead it updates bookmark and bookmark-it icon in Window Y.

bookmark-it/background.js relies on `tabs.onUpdated` and `tabs.onActivated` events to update the icon on-off state and stores active tab/bookmark in `currentTab`, `currentBookmark` variables; for the `browserAction.onClicked` event it relies on those variables, but when using multiple windows those variables are not updated correctly.

I'm not sure how to solve this, other than bite the bullet, get rid of those variables, and re-run both `tabs.query({active: true, currentWindow: true})` and ` bookmarks.search()` in the browser action toggle function?

That might actually make the code shorter as `updateActiveTab()` and `toggleBookmark()` would be using the same logic then, so it could use the same function just with a toggle flag added. As a side effect it should also do the right thing if a bookmark was created/removed in the meantime while current bookmark-it still remembers a bookmark that no longer exists.

But I'm not sure if that is the correct solution.

**Comment by wbamberg** [comment]
Thanks for filing, and for thinking about a fix! I'm afraid I didn't get a chance to think in detail about a solution. But [browserAction.onClicked passes the Tab for the current tab to its listener](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/onClicked#addListener_syntax). Perhaps you could do something like:

* on click, get passed the current tab. Toggle its state (if your tab's icon is "star-filled", unbookmark it and switch icon, otherwise bookmark it and switch icon).

* when the active tab changes: get the active tab ID, then use it to search bookmarks, and use the result to set the icon.

?

I agree that it would be nice to get rid of those variables, they seem like asking for trouble.
