### ISSUE TITLE
checkbox not visible in nightly

### ISSUE THREAD

**Issue by def00111** [mdn/webextensions-examples#214]
Install this add-on: https://addons.mozilla.org/firefox/addon/block-site-2/

Go to options, you will see the checkboxes are not visible.

Using Nightly 55.0a1 (2017-04-29) (32-bit)

**Comment by wbamberg** [comment]
Please use this tracker to report issues with the example add-ons in this repo, not to report general add-ons issues. The page you link to says "Note: in order to report bugs, please visit addon homepage and fill the bug report form", linking to http://mybrowseraddon.com/block-site.html. So perhaps you should try asking there for support about this particular add-on.

**Comment by def00111** [comment]
This problem also occurs with other add-ons.
The forget-it add-on also has this problem.
the checkbox is not visible.

**Comment by wbamberg** [comment]
Thanks for the extra information!

I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1361084 for this. It looks like it might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1354336, only in that bug the checkboxes we just inactive, not invisible.
