### ISSUE TITLE
difficulties with examples

### ISSUE THREAD

**Issue by jtg567** [mdn/webextensions-examples#254]
The following messages appear in the console when trying to click animals in the pop-out for Beastify. I'm running using web-ext with the --bc command line arg:

`Error: No window matching {"matchesHost":["<all_urls>"]}`

`Error: Could not establish connection. Receiving end does not exist.`

```
"application": {
    "architecture": "x86-64",
    "buildId": "20170628075643",
    "name": "Firefox",
    "version": "54.0.1",
    "displayVersion": "54.0.1",
    "vendor": "Mozilla",
    "platformVersion": "54.0.1",
    "xpcomAbi": "x86_64-msvc",
    "channel": "release"
  },

      "os": {
        "name": "Windows_NT",
        "version": "10.0",
        "locale": "en-US",
        "servicePackMajor": 0,
        "servicePackMinor": 0,
        "windowsBuildNumber": 15063,
        "windowsUBR": 483,
        "installYear": 2017
      },
```

**Comment by jtg567** [comment]
borderify definitely didn't work with the first mozilla.org domain page I loaded

after adding a console.log statement and reloading the extension from the web-ext command line prompt I got a border

**Comment by wbamberg** [comment]
Which page, please?

**Comment by jtg567** [comment]
@wbamberg - https://www.mozilla.org/en-US/

**Comment by wbamberg** [comment]
I can't reproduce this. Using `web-ext --bc`, borderify works fine for me on https://www.mozilla.org/en-US/.

I'm not sure what could make it work again after adding a console.log and reloading. Does it stop working again if you remove the console log statement?

There is a bug in borderify which I'm trying to fix in https://github.com/mdn/webextensions-examples/pull/240, which will often (always?) cause the first click on a beast in the popup to fail. But you won't see "" - that's much more likely to be because you're trying to beastify a page that's blocked content scripts, such as about:debugging or https://addons.mozilla.org/en-US/firefox/.

**Comment by jtg567** [comment]
When I install `context-menu-demo` from about:debugging I get this message:
```
There was an error during installation: Add-on d5054935b0617c143a28cea00eb95f832db79af1@temporary-addon is not compatible with application version. add-on minVersion: 55.0a1.
```
Similarly, when I try to run `web-ext run --bc` from the directory I see the following:

```
run: WebExtError: installTemporaryAddon: Error: unknownError: Could not install add-on at 'C:\GitHub\mdn\webextensions-examples\context-menu-demo': Error: Add-on c7a9611369c1f8cfaf387b87e8fdfeebb26efaa8@temporary-addon is not compatible with application version. add-on minVersion: 55.0a1.
    at C:\Users\Josh Gaunt\AppData\Roaming\npm\node_modules\web-ext\dist\webpack:\src\firefox\remote.js:9:13549
    at EventEmitter.extend.handleMessage (C:\Users\Josh Gaunt\AppData\Roaming\npm\node_modules\web-ext\node_modules\node-firefox-connect\node_modules\firefox-client\lib\client.js:161:7)
    at EventEmitter.extend.readMessage (C:\Users\Josh Gaunt\AppData\Roaming\npm\node_modules\web-ext\node_modules\node-firefox-connect\node_modules\firefox-client\lib\client.js:220:10)
    at EventEmitter.extend.onData (C:\Users\Josh Gaunt\AppData\Roaming\npm\node_modules\web-ext\node_modules\node-firefox-connect\node_modules\firefox-client\lib\client.js:186:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

**Comment by wbamberg** [comment]
That's because you're using Firefox 54, and this example uses features that are new in Firefox 55: https://github.com/mdn/webextensions-examples/blob/master/context-menu-demo/manifest.json#L10.

From the docs:

`A few examples rely on APIs that are currently only available in pre-release versions of Firefox. Where this is the case, the example should declare the minimum version that it needs in the strict_min_version part of the applications key in its manifest.json file.`
