### ISSUE TITLE
beastify needs a review

### ISSUE THREAD

**Issue by wbamberg** [mdn/webextensions-examples#28]
https://github.com/mdn/webextensions-examples/tree/master/beastify.

**Comment by bwinton** [comment]
* The [README](https://github.com/mdn/webextensions-examples/blob/master/beastify/README.md) could use some content, describing what this add-on does, and why, and what it is trying to demonstrate.
* In [the content script](https://github.com/mdn/webextensions-examples/blob/master/beastify/content_scripts/beastify.js) it seems a little odd to add `beastify` as a listener before it's defined.  (I know it works because functions get hoisted to the top, but changing the declaration to `var beastify = function () {…` which should be the same, will break it.)
* I also kind of feel like the call to `chrome.extension.getURL` should happen in the popup code, because it feels less like a content thing to me, but I appreciate that this point is pretty arbitrary.  :wink:

**Comment by wbamberg** [comment]
Thanks @bwinton ! I've just committed: https://github.com/mdn/webextensions-examples/commit/d552033b78cc2d32774e0a42ae536119956ce50c which should fix these.
