### ISSUE TITLE
beastify vs borderify

### ISSUE THREAD

**Issue by losnappas** [mdn/webextensions-examples#283]
Wouldn't it just make a lot more sense if Borderify used executeScript and Beastify used the manifest way?

**Comment by wbamberg** [comment]
Why?

**Comment by losnappas** [comment]
In my opinion, Borderify is too simple as is. On the other hand Beastify seems like a mess. Besides, isn't executeScript's second main point to inject css? If Beastify was using manifest method, the browser.tabs.reload would be taken care of and perhaps it could fix this problem `Close the popup. This is needed, as the content script malfunctions after page reloads.`?

And by the way, just noticed
```javascript
browser.tabs.executeScript(null, {
      file: "/content_scripts/beastify.js"
    });

    var gettingActiveTab = browser.tabs.query({active: true, currentWindow: true});
    gettingActiveTab.then((tabs) => {
      browser.tabs.sendMessage(tabs[0].id, {beastURL: chosenBeastURL});
    });
```
needs to be
```javascript
browser.tabs.executeScript(null, {
      file: "/content_scripts/beastify.js"
    }).then(()=>{

      var gettingActiveTab = browser.tabs.query({active: true, currentWindow: true});
      gettingActiveTab.then((tabs) => {
        browser.tabs.sendMessage(tabs[0].id, {beastURL: chosenBeastURL});
      });
    });
```
or it will glitch when sendMessage happens before injecting

**Comment by wbamberg** [comment]
> In my opinion, Borderify is too simple as is.

Too simple for what? It's supposed to be simple, so it can work as a very basic introduction to the extension development workflow.

> On the other hand Beastify seems like a mess.

This doesn't seem like an actionable statement.

> Besides, isn't executeScript's second main point to inject css? 

No, that's [insertCSS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/insertCSS).

> If Beastify was using manifest method, the browser.tabs.reload would be taken care of and perhaps it could fix this problem Close the popup. This is needed, as the content script malfunctions after page reloads.?

I don't understand this point.

> And by the way, just noticed...

Yes, there's a bug here, that https://github.com/mdn/webextensions-examples/pull/240 is supposed to fix.

**Comment by losnappas** [comment]
Sorry. To me, Beastify 'seems like a mess' because it doesn't have a background script, instead injects from the options script.
As for point: there would be no need for `window.close();` in choose_beast.js if one injected via manifest.

**Comment by wbamberg** [comment]
It doesn't have a background script because it doesn't need one, because it uses a popup instead. I'm not sure what alternative design, that uses a background script, you are proposing.

It doesn't use the `content_scripts` manifest key because that would inject the script for every page the user loads, which would be inefficient if the user only actually beastifies a small number of pages.

The `window.close()` thing is unfortunate, yes. I don't know why the popup stops working if you reload the page. I don't know if it would work if you use the  `content_scripts` manifest key instead of executeScript, but I doubt it, and I don't think that is a good reason in itself to switch to`content_scripts`.
