### ISSUE TITLE
Beastify xpi problem

### ISSUE THREAD

**Issue by linhnhuonglt** [mdn/webextensions-examples#3]
How to build xpi file from your Beastify folder ?
I tried to use your sample in github and zipped to be zip file . Then , i renamed it to xpi file but it was not working in my firefox .

**Comment by jceation** [comment]
i got some error like you .
![error](https://cloud.githubusercontent.com/assets/14744230/10014525/094ca32a-6144-11e5-9746-014f72312139.png)

**Comment by wbamberg** [comment]
beastify does not work in Firefox, yet, because of outstanding bugs. But it should install. Could you somehow make your XPI available to me, and I'll take a look?

**Comment by jceation** [comment]
@wbamberg Thanks for your replies
Because my command line cannot understand 'zip' keyword , I tried to zip by clicking on right mouse and selecting "add to archive" then rename this file from .zip to .xpi  . so I got borderify.xpi . I think it make problem .

My borderify.xpi in https://drive.google.com/file/d/0Bxth9u5D0bPBUVFndkktUzhWQWM/view?usp=sharing

**Comment by wbamberg** [comment]
@jceation, I can't open this XPI using command-line zip :(. I get this error: 

    End-of-central-directory signature not found.  Either this file is not
    a zipfile, or it constitutes one disk of a multi-part archive.  In the
    latter case the central directory and zipfile comment will be found on
    the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of b.zip or
        b.zip.zip, and cannot find b.zip.ZIP, period.

Are you running Windows? Unfortunately I don't have a Windows environment I can try this out with. Could you perhaps try installing 7-zip (http://www.7-zip.org/) and see if you can zip the files from the command line using that? There's a useful-looking guide here: https://stackoverflow.com/questions/19240653/how-to-create-xpi-file-with-7zip. I think the command-line version on Windows would be this:

7z a ..\<extension_name>.xpi * -r

**Comment by jceation** [comment]
@wbamberg,
Thank you very much ! You save my life :+1:

**Comment by eKivOxhd** [comment]
Hello , i have the same problème , i use command line 7z a ..\beastify.xpi * -r, make an xpi file , when i drop it in Mozilla , it tell me : This addon could not be installed because it appears to be corrupt.

How can i put it in Mozilla ? The file is good ?

Thx in advance!

(French locale)
<img width="691" alt="capture" src="https://cloud.githubusercontent.com/assets/14998241/10311524/62ce805e-6c47-11e5-9753-c48507b9b7bc.PNG">

**Comment by wbamberg** [comment]
@eKivOxhd, could you somehow make your XPI available to me, and I'll take a look?

**Comment by eKivOxhd** [comment]
Hello , my xpi  : https://drive.google.com/open?id=0B7oV2LehKzeoWXJ0RjcyT3NfX1U i don't know why it doesn't work :( , and a question for you , On trello i saw you have to do WebExtension , and i want to know when WebExtension will be done ? Thx Wbamberg !

**Comment by wbamberg** [comment]
The XPI you shared installs for me in Firefox Nightly (44).

> On trello i saw you have to do WebExtension
> and i want to know when WebExtension will be done ?

I'm just writing the docs, not implementing the thing. I think we are still working out when v1.0 of WebExtensions will ship.

**Comment by eKivOxhd** [comment]
Hi ! Ok i wasn't try on Nightly but , think you Webextension will be avaliable on FireFox (40+) this year?

Thank you for Having taken time to take care of my problem!

**Comment by wbamberg** [comment]
What's currently in Nightly will (probably) be in release Firefox at the end of January 2016 (see https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates). But what's currently in Nightly is definitely not a 1.0 release of WebExtensions, yet: it's still experimental.

I'm pleased that helped, and am closing this for now.
