### ISSUE TITLE
apply-css.js example shows icons on every tab. 

### ISSUE THREAD

**Issue by pmario** [mdn/webextensions-examples#309]
Hi folks, 
I'm new here. 

I did just test the https://github.com/mdn/webextensions-examples/tree/master/apply-css example with FF 58.0b1 developer edition. 

Whatever I do set here: https://github.com/mdn/webextensions-examples/blob/master/apply-css/background.js#L4 ... I always get icons for every tab.

**Comment by wbamberg** [comment]
Yes, I see this too. It seems to be a change from version 57 (the current Beta). In 58 Firefox is showing the page action by default (I think the conditional is working and https://github.com/mdn/webextensions-examples/blob/master/apply-css/background.js#L43-L45 isn't running, because the icon's title is not being set).

@andymckay , are you aware of a change in Nightly to show the page action by default?

**Comment by andymckay** [comment]
Yes, its part of this bug tree: https://bugzilla.mozilla.org/show_bug.cgi?id=1395387 and is being fixed. I believe the intent is to show the icon visible but in a clearly disabled state. If you want more information  follow along those bugs.

**Comment by pmario** [comment]
Thx for the info. ... Just good to see, that it's a known issue. have a nice day!
