### ISSUE TITLE
Missing an example of a native looking popup

### ISSUE THREAD

**Issue by blaise-io** [mdn/webextensions-examples#318]
There's the [Beastify](https://github.com/mdn/webextensions-examples/tree/master/beastify/popup) example that demonstrates a popup, but it doesn't look native and it doesn't use any of the CSS provided in `chrome://browser/content/extension.css`.

I'm looking for something that looks like this:
![native looking](https://i.imgur.com/DSL5r0u.png)

Are there html/css examples (or documentation) for achieving this?

**Comment by wbamberg** [comment]
There are lots of examples, search for `"browser_style": true` in manifest.json.

There are a few pointers to using this on MDN: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action but I don't want to document it fully there because:

(1) the specific styles you can use are Firefox-specific, and the MDN docs aim to be cross-browser (as far as possible)

(2) it's not obvious to me that Mozilla is committed to supporting `extension.css` as a public API, so I'm not sure how far people should rely on the classes it defines.

**Comment by blaise-io** [comment]
Thanks for your reply @wbamberg.

I also did some research after creating this issue: [In this mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1225633), Blake Winton created styling defaults in `extension.css`. From reading the bug description and comments, it seems that the intent was that addon developers could create native-looking UIs using the styles defined in that file.

However, the file never implemented all aspects of the Firefox UI, and two years later, the file is outdated as some styles have changed.

Currently, the menu styles defined in `browser_style` are useful as a base, but I still have to go though  trial and error to figure out how the HTML nesting is supposed to be for those styles, and I have to add my own CSS to make my addon's popup menus look like the built-in Firefox menus.

**Comment by wbamberg** [comment]
Closing this - I don't plan to add an example here, because I don't think Mozilla is committed to supporting `extension.css` as a public API, so it will probably just break.
