### ISSUE TITLE
open-my-page-button with hash containing %3A in URL fails

### ISSUE THREAD

**Issue by pepri** [mdn/webextensions-examples#32]
When I use a hash value in URL with a colon (%3A) (e.g. `chrome.extension.getURL("my-page.html#%3A")`), the opened page shows "The address isn't valid".

Not sure whether this is right place to report this bug, but there were no answers on IRC and I am not familiar with mailing lists, so I am leaving it here.

**Comment by wbamberg** [comment]
It looks as if what's happening here is: the code is trying to resolve the supplied argument relative to the extension's base URI. It's doing that by passing the argument through to nsIURI.resolve(), and returning the result of that call: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ext-extension.js#7.

When the given argument contains ":", for example "my:page.html", then baseURI.resolve() is just returning the argument unchanged. We then try to load that as a complete URL, and complain because it's not a valid URL.

Is it perhaps because resolve() doesn't think the argument is a relative URI if it contains ":"?

The equivalent code works in Chrome.

**Comment by wbamberg** [comment]
Filed bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1242080
