### ISSUE TITLE
unrealistic examples

### ISSUE THREAD

**Issue by cmroanirgo** [mdn/webextensions-examples#324]
I was checking out the `webpack-modules` example and was shocked to find that node_modules blew out to 350+MB:

```
$ du -d1 -h
 32K	./extension
358M	./node_modules
 20K	./src
358M	.
```

I think it reasonable to assume that there's something seriously wrong with the way the dependencies are constructed for such a ridiculously large download!

**Comment by wbamberg** [comment]
I'm not sure which example you're talking about - webpack-modules doesn't have a ./extension directory.

I see this:
```
$ du -d1 -h
 32K	./addon
4.0K	./background_scripts
 32M	./node_modules
4.0K	./popup
 32M    .
```

32MB is still a lot but it's all coming from the webpack dependency itself. Since the example is to demonstrate webpack I'm not sure how you would optimize this away.

Also, this isn't going into the built extension - that's all inside `./addon`, which is 32K, or 7K compressed.

**Comment by cmroanirgo** [comment]
Sorry. This `webextensions-examples/store-collected-images/webextension-with-webpack/`

**Comment by wbamberg** [comment]
I still see slightly different numbers. After `npm install` but before `npm run build`:

```
$ du -d1 -h
 32K	./extension
111M	./node_modules
 20K	./src
111M	.
```

After `npm run build`:

```
$ du -d1 -h
3.8M	./extension
111M	./node_modules
 20K	./src
115M	.
```

111MB is big, sure, that's because it's using Babel and Webpack and React. I wonder why you are getting more than three times this amount.

Again these aren't going into the built extension though. I'd be more worried about the 3.8MB size of the built extension (coming down to about 1MB compressed).

There are some deprecation warnings also:

```
npm WARN deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated fs-promise@0.3.1: Use mz or fs-extra^3.0 with Promise Support
```

@rpl , what do you think?

**Comment by cmroanirgo** [comment]
I've deliberately held back my npm version to <3 (to keep away from the flat 'node_modules' issue). I also see this warning as part of `npm install`:

`npm WARN engine web-ext@1.9.1: wanted: {"node":">=4.0.0","npm":">=3.0.0"} (current: {"node":"6.9.2","npm":"2.15.11"})
`

Note sure if such a thing would warrant an extra 240MB though!

I'm aware that the extensions folder should be small by comparison. I have not done an `npm build`.

**Comment by rpl** [comment]
@wbamberg @cmroanirgo I took a look at the numbers locally and which files are actually the ones that contribute more to the total size (after the extension has been built using npm run build):

```
$ du -hs extension/*

1.7M	extension/dist
18K	extension/images
4.5K	extension/manifest.json
4.5K	extension/navigate-collection.css
4.5K	extension/navigate-collection.html
4.5K	extension/popup.css
4.5K	extension/popup.html
4.5K	extension/shared.css
```

The dist this is clearly the bigger one (nevertheless the size of my extension dir seems to be smaller than @wbamberg ones, do you mind to run a du on the content of the extension dir on your development environment?), and the content of the dist dir is the following:

```
$ du -hs extension/dist/*

4.5K	extension/dist/background.js
4.5K	extension/dist/background.js.map
297K	extension/dist/navigate-collection.js
545K	extension/dist/navigate-collection.js.map
297K	extension/dist/popup.js
549K	extension/dist/popup.js.map
```

And so, 1MB of the total 1.7MB seems to be just the source maps of the bundled files, clearly just the ones that have actually have a dependency (react) bundled in the js file by webpack.

The size of the build file (e.g. using web-ext build -s extension) is:

```
$ du -hs web-ext-artifacts/store-collected-images-1.0.zip

953K	web-ext-artifacts/store-collected-images-1.0.zip
``` 

While if we exclude the source maps file from the build extension (e.g. using `web-ext build -s extension -i 'dist/*.map'`):

```
$ du -hs web-ext-artifacts/store-collected-images-1.0.zip

345K	web-ext-artifacts/store-collected-images-1.0.zip
```

It would be probably possible to reduce the size of the bundle file by configuring webpack to share the bundled react (and its dependencies) into a separated file (which have to be loaded before the bundle that is going to use it), paying it by some additional configuration in the webpack config file (and probably an additional npm dependency, and some additional space used in `node_modules/ as a side effect).

As @wbamberg already mentioned in his comment, the size of the `node_modules/` dir doesn't affect directly the size of the extension (we could define it the size of the development environment of such extension).

The size of the `node_modules/` dir on my system (node 6 / npm 3), is:

```
$ du -hs node_modules

94M	node_modules
```

Using an npm version older than npm 3 provides a "more deterministic" development environment at the cost of much more disk space used (because of the multiple copies of the npm dependencies, which are on the contrary shared on npm >=3 because the tree of the npm dependencies is "flattened").

I can completely understand (I had to investigate very weird side-effect of the "non deterministic" flattening of the npm dependencies, unfortunately you are not always in the position of being able to make that choice, e.g. you can't if the npm package has to be installed by arbitrary users which may have different nodejs/npm version combinations)  a developer that decides to stick to a "non flattening" npm version, but at the same time I would not be surprised of the considerable bigger size of the resulting `node_modules/` dir.

**Comment by rpl** [comment]
@wbamberg @cmroanirgo it is worth to mention that, if the size of the `node_modules/` is important for a developer that doesn't have a big amount of disk size of his/her system, a good start is "removing from the `package.json` file related to the particular extension development environment all the command line tools" (e.g. webpack and web-ext in this case), and install then globally (using `npm install -g`).

**Comment by ewnd9** [comment]
If anyone is struggling with disk space they could try https://github.com/pnpm/pnpm

It links dependencies instead of copying.

Also, instead of deleting `devDependencies` one could install with `--production` flag (only `dependencies`) and then manually install build tools globally.

**Comment by cmroanirgo** [comment]
My primary concern based around limited download bandwidth. 50MB for a demo is barely acceptable, 100MB is probably not. 250MB is definitely not.

Don't forget that we're talking about a _WebExtension_. That is, the end result is small (ie the `extension` folder), so why should it take almost _2 orders of magnitude_ more space to provide that download?
There is something wrong with the build model in this case... surely!?

**Comment by ewnd9** [comment]
Yes, 250MB is due to the obsolete npm version which does not deduplicate dependencies.

100mb+ (with dedup) is quite common for webpack+babel and dependencies are cached locally so with every new project you are downloading less.

It's not necessary in order to build apps, just what some people find convenient.

**Comment by cmroanirgo** [comment]
Clearly by the responses, this case will end up in a "don't care, won't fix" box. _C'est a vie._

**Comment by ewnd9** [comment]
I'm afraid there is nothing to fix. Example without dependencies is presented (`/store-collected-images/webextension-plain`) and you could compare the dependencies weight with other similar projects or just by installing minimal amount of dependencies yourself to ensure nothing is extraordinary in *this particular example*:

```sh
$ npm install webpack react react-dom babel-preset-react babel-loader --save-dev # 48mb with npm@5
```

**Comment by wbamberg** [comment]
@rpl, @ewnd9 , thanks for the extra analysis.

> (nevertheless the size of my extension dir seems to be smaller than @wbamberg ones, do you mind to run a du on the content of the extension dir on your development environment?), and the content of the dist dir is the following:

```
$ du -hs extension/dist/*
4.5K	extension/dist/background.js
4.5K	extension/dist/background.js.map
297K	extension/dist/navigate-collection.js
545K	extension/dist/navigate-collection.js.map
297K	extension/dist/popup.js
549K	extension/dist/popup.js.map
```


I get this:

```
$ du -hs extension/dist/*
8.0K	extension/dist/background.js
8.0K	extension/dist/background.js.map
716K	extension/dist/navigate-collection.js
1.2M	extension/dist/navigate-collection.js.map
720K	extension/dist/popup.js
1.2M	extension/dist/popup.js.map
```

> "don't care, won't fix"

As @ewnd9 says, this is not really accurate. FWIW I agree with you that the size is excessive, but unless there is some problem with the way this extension is listing its dependencies that causes the bloat, this is just what you get when you depend on Babel and React and Webpack. So the only "fix" is: don't use these tools. But people want examples of using the tools to develop extensions, which is the purpose of including this example alongside the `-plain` one.
