### ISSUE TITLE
Commands example is working on Mac

### ISSUE THREAD

**Issue by paul-hammant** [mdn/webextensions-examples#331]
The extension tries to register Command-Shift-U and if that is pressed, print something to the console. Doesn't work for me on MacOS 10.13.2, Firefox 57.0.3.  

To reproduce it I am doing `web-ext run --verbose` in the `commands` directory after git-clone and a cd into it.

* Yes I'm aware that it is Cmd-Shift-U on the Mac not Ctrl-Shift-U.
* I've tried other key combos, and watched the extension reload in via terminal output, but its still not working
* I can confirm that other extensions like bookmarkit (also in this repo) work fine
* I can confirm that also isnt working in FirefoxDeveloperEdition 58.0b13 and Firefox Nightly 59.0a1 (2017-12-29) 

I note that https://support.mozilla.org/en-US/questions/1178120 had the same problem, but noted it went away when they got a new machine. At least they circled back with an update - so rare these days :(

**Comment by wbamberg** [comment]
Thanks for the report.

The extension works for me (OS X, Firefox Nightly, both with web-ext and about:debugging).

You said "https://support.mozilla.org/en-US/questions/1178120 had the same problem" - in that report, no Firefox shortcuts that contained the Command key worked - so it wasn't specific to extensions. Is that also your situation?

Is it possible that you are looking in the normal web console, rather than the console in the [Add-on debugger](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#The_Add-on_Debugger)?

Some things to try:

1) the example also logs registered shortcuts to the console when it is installed, like this:

```
Object { name: "toggle-feature", description: "Send a 'toggle-feature' event to th…", shortcut: "Alt+Shift+U" }
```

Do you see that?

2) try changing the example to do something different, like:

```
// background.js
browser.commands.onCommand.addListener((command) => {
  browser.tabs.create({url: "https://developer.mozilla.org"});
});
```

If that works, then the problem is with logging.

3) try a different keyboard shortcut, like:

```
  "commands": {
    "toggle-feature": {
      "suggested_key": { "default": "Alt+Shift+U" },
      "description": "Send a 'toggle-feature' event to the extension"
    }
  }
```

or:

```
  "commands": {
    "toggle-feature": {
      "suggested_key": { "default": "Ctrl+Shift+K" },
      "description": "Send a 'toggle-feature' event to the extension"
    }
  }
```

That would establish whether it's specific to a particular shortcut.

**Comment by paul-hammant** [comment]
Super detailed reply - thanks.

I'm going to check now, but I suspect I was looking in the wrong console.... will report back.

**Comment by paul-hammant** [comment]
Yup that was it. 'Browser Console' had it whereas the apps console did not (as you said):

    "onCommand event received for message:  toggle-feature"

If I'd tried a classic `alert("I hapened")` I would have caught it myself. Instead I wasted hours of my time, and 20 mins of your time too. #ThisIsWhyPairProgrammingPaysForItself or #ShouldntBeCodingInTheHolidayPeriod

I suggest a comment in the code because that's a classic noob mistake - seeing `console.log(..)` in source and thinking *I know that thing*  ?

**Comment by wbamberg** [comment]
I think it might be better for the example to open a new tab in `onCommand`, like in my comment above, rather than log a string to the console. The different consoles thing confuses everybody, but even that aside, it would be better IMO for examples to have a more obvious payoff than console output.

What do you think?

**Comment by paul-hammant** [comment]
Agreed

**Comment by wbamberg** [comment]
-> https://github.com/mdn/webextensions-examples/pull/332#pullrequestreview-86430173

Thanks for filing. It may have been a waste of your time, but it wasn't time wasted, since I think the example is better this way :).

**Comment by paul-hammant** [comment]
Ah now, time spend programming while not pairing has the potential to waste my time (take longer than if paired)!  Filing bugs is never a waste:)
