### ISSUE TITLE
"buttons" is not working in Web extensions create function options

### ISSUE THREAD

**Issue by sriharrsha** [mdn/webextensions-examples#340]
Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create.

"buttons" is not working in Web extensions create function options

**Comment by wbamberg** [comment]
Firefox does not support buttons in notifications: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions

**Comment by harrshasri** [comment]
@wbamberg What to do for Notification on click for firefox?

**Comment by wbamberg** [comment]
I'm not sure I understand the question, can you explain in a bit more detail? Also, this is not a forum for WebExtension support questions, it's better to ask support questions in the [Discourse forum](https://discourse.mozilla-community.org/c/add-ons/development).

**Comment by wbamberg** [comment]
No problem, thanks for the clarification.

[`onClicked`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/onClicked) is supported. It listens for any click on the notification. [`onButtonClicked`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/onButtonClicked) is not supported, because in Firefox you can't create notifications that contain buttons.

**Comment by strongop** [comment]
Then why this doc says buttons is supported?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions

**Comment by strongop** [comment]
Well the "buttons not supported" is hidden in the `Browser compatibility` section.
So confusing.
