### ISSUE TITLE
Do not use innerText

### ISSUE THREAD

**Issue by rugk** [mdn/webextensions-examples#351]
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent explains the differences to `innerText`, which does not seem to be preferred and is a thing IE invented.

You should use `textContent` instead.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Security_best_practices also advocates for `textContent`:
> insert strings using safe native DOM manipulation methods: document.createElement, Element.setAtttribute, and Node.textContent.

**Comment by gkrishnaks** [comment]
Hi, 
Google extension developer documentation recommends innerText:

" Instead, manually create DOM nodes and use innerText to insert dynamic content" 

https://developer.chrome.com/extensions/security

I didn't (yet?) find a similar page in Mozilla extensions documentation.

**Comment by wbamberg** [comment]
The Chrome page is primarily telling people not to use `innerHTML` on unsanitised content, which everyone agrees  on, [including the MDN docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Safely_inserting_external_content_into_a_page). The Chrome page offers `innerText` as an alternative, but it's not obvious to me that this is better than `textContent` or if so why.

Conversely, using `innerText` rather than `textContent` doesn't seem to be a very big problem either, and I don't see anything in https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent to indicate that it is. If you can explain why it's a big problem I'd be happy to learn about it. Until then, while I'd review a PR that changed `innerText` to `innerHTML`, I don't think it's a high priority to make the change.

**Comment by rugk** [comment]
Uh, indeed I did not carefully read that part about `innerText`. You indeed do not use the problematic `innerHtml`, so everything is fine.

But BTW I would still be curious about the differences between `textContent` and `innerText`.
