### ISSUE TITLE
Example with right-click menu entry?

### ISSUE THREAD

**Issue by uswoods** [mdn/webextensions-examples#392]
Which of these examples features a right-click menu entry, which may be used for executing a link on the (mouse) selection?

**Comment by David263** [comment]
The example may not be here, but at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Modify_a_web_page . It uses "contextMenus" permissions and browser.contextMenus.create() .

**Comment by bytecauldron** [comment]
These examples may have popped up over the last few years since this issue was originally created.
Both [context-menu-copy-link-with-types](https://github.com/mdn/webextensions-examples/tree/master/context-menu-copy-link-with-types) and [menu-demo](https://github.com/mdn/webextensions-examples/tree/master/menu-demo) demonstrate the use of context menus. Can we close this issue, or do you need this specific example created?
