### ISSUE TITLE
Link "notify-link-clicks" down

### ISSUE THREAD

**Issue by julmot** [mdn/webextensions-examples#43]
The link to the correct repository is wrong:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples

**Comment by wbamberg** [comment]
Yes, sorry, that page hasn't been very well maintained.

(Specifically, I removed "notify-link-clicks" because it was pointed out that it contains nothing that "notify-link-clicks-i18n" didn't have. But there are some new examples that are also missing from that page.)

I just updated it to generate the content from the descriptions of the examples, so it should be up to date now.
