### ISSUE TITLE
Borderify isn't working

### ISSUE THREAD

**Issue by Rocketblaster247** [mdn/webextensions-examples#437]
I've downloaded the repo. Made my own. Nothing is working.

**Comment by rebloor** [comment]
Hi @Rocketblaster247 I've pulled the latest version of the repo and get the expected behavior from Borderify, a red border is added to mozilla.org pages, in the developer edition of Firefox (72). Can you provide some more information about your issue, e.g. what steps you took to make your own, which version of Firefox etc. Thank you

**Comment by Rocketblaster247** [comment]
Maybe its got to do with Firefoxe's settings. Sorry for the inconvenience. I'll try to fix it by myself.

**Comment by rebloor** [comment]
No inconvenience @Rocketblaster247 good luck!
