### ISSUE TITLE
browser is not defined

### ISSUE THREAD

**Issue by ginokai** [mdn/webextensions-examples#492]
history-deleter error in all Windows 11 Pro Version 10.0.22000 Build 22000 browsers:
- Edge Version 101.0.1210.53 (Official build) (64-bit), 
- Chrome Version 101.0.4951.67 (Official Build) (64-bit), 
- Firefox 100.0.2 (64-bit)
history.js:24 Uncaught ReferenceError: browser is not defined

line 24 of history.js:
return browser.tabs.query({active: true, currentWindow: true});

Can you help?
P.S. Safari and Chrome on iPadOS 15.5 also don't work, however I cannot see the error message but it's presumably there

**Comment by rebloor** [comment]
@ginokai this issue log is intended for problems with the with web extension examples. Your issue seems to be a more general Windows issue. You might try posting in the [MDN forum](https://discourse.mozilla.org/c/mdn/236) or contacting Microsoft

**Comment by Rob--W** [comment]
`browser` is defined for sure if the code is running in an extension, in Firefox and Safari. The `browser` API is not available to regular (non-extension) web pages.

For Chrome and Edge, you'd need the webextension-polyfill (https://github.com/mozilla/webextension-polyfill) in order to use `browser`.

For general extension documentation, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions.
