### ISSUE TITLE
Can't get response in Ubuntu

### ISSUE THREAD

**Issue by yigitcanustek** [mdn/webextensions-examples#506]
I _tried_ every solution path in MDN Native Messaging Docs
(https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging 
also
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests)
but can't get response from ping_pong.py. 

I copied ping_pong.json(also manifest.json too cause clearly not working with ping_pong.json) that specified in docs, can't response in either. By the way, i must tell that some folders didn't exist while i was trying to copy(e.g. /usr/lib/mozilla/native-messaging-hosts). So i created that folder and copied ping_pong.json to there and still can't get response. 

The last thing i need to mention, i need to deleted Firefox, before because the snap installation causes problem to Firefox to find profiles. I removed Firefox then installed without snap installation and able to run Firefox for profile changes seamlessly.

**Ubuntu version:**
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Firefox version:**
Mozilla Firefox 107.0.1

**Comment by higba** [comment]
I am having the same issue but I am running MacOS Monterey 12.6. Mozilla Firefox version 108.0.  There is no error, the extension is sending but no response from the application.

**Comment by guest271314** [comment]
`python` alone is not an executable in Ubuntu. 

```
$ find /usr/bin/python
find: ‘/usr/bin/python’: No such file or directory
```

I filed https://github.com/mdn/webextensions-examples/pull/490 to fix that issue.

Try substituting 

```
#!/usr/bin/env -S python3 -u
```

for 

```
#!/usr/bin/env python
```

**Comment by yigitcanustek** [comment]
Nope. Still not working.

Also 
`$ find /usr/bin/python`
returns
`/usr/bin/python`

And yes, i checked the permissions and they all have execute permission.

I think, this is not about Python. Somehow, Firefox is not reading the .json files and can't communicate each other.

**Comment by guest271314** [comment]
The last time I tested on Nightly it worked. I'll test again later today or tomorrow.

**Comment by yigitcanustek** [comment]
Okey. I'll wait the test result but i want to ask where do you put manifest file? I am asking this question because 

/usr/lib/mozilla/native-messaging-hosts/<name>.json

and

/usr/lib64/mozilla/native-messaging-hosts/<name>.json

the mozilla folder didn't exist. So, manually created by myself. I think, this issue related to this configuration. Briefly, how to configure this environment? Can you provide ur configurement verbosely?

**Comment by guest271314** [comment]
Neither. I removed the snap Firefox installation. Then removed snap altogether and fetched Nightly and created the file in ~/.mozilla.

**Comment by guest271314** [comment]
I created this 

```
~/.mozilla/native-messaging-hosts/<name>.json
```

per https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#linux.

**Comment by guest271314** [comment]
1. Include error handling in background.js (and optionally just log the port) so you know what is going on
```
let port = browser.runtime.connectNative("ping_pong");
console.log(port);
// Include error handling so we know what is going on
port.onDisconnect.addListener((err) => {
  if (browser.runtime.lastError) {
    console.warn(browser.runtime.lastError);
  }
  console.error(err.name, err.message);
});
```
    
2. Create the directory `native-messaging-hosts` in `~/.mozilla`;
3. Open the file `ping_pong.json`, write the full path on the filesystem to `ping_pong.py` at `"path"` value, e.g.,
  
```
{
  "name": "ping_pong",
  "description": "Example host for native messaging",
  "path": "/home/user/native-messaging/app/ping_pong.py",
  "type": "stdio",
  "allowed_extensions": [ "ping_pong@example.org" ]
}
```

4. Open `ping_pong.py` and substitute the following shebang for the one in the file, to avoid any ambiguity as to which executable is being called; the `-S` passed to `env` enables passing options to the executable called
 
> -S, --split-string=S  process and split S into separate arguments;
                        used to pass multiple arguments on shebang lines


in this case `-u`, for `

> -u     : force the stdout and stderr streams to be unbuffered;
         this option has no effect on stdin; also PYTHONUNBUFFERED=x


```
#!/usr/bin/env -S python3 -u
```

because I do not have the executable `python` is installed on my machine. If you have the executable `python` installed on your machine; then omit step 4.;
5. `cd` to the `app` directory and make sure `ping_pong.py` is marked executable `$ chmod u+x ping_pong.py`;
6. On Firefox or Nightly navigate to `about:debugging`, click "This Nightly" or "This Firefox", select the "Load Temporary Add-on...", select `manifest.json`;
7. Click "Inspect";
8. Pin the icon to the toolbar if not already automatically pinned, then click the icon.

![Screenshot_2023-01-02_21-18-59](https://user-images.githubusercontent.com/4174848/210306571-5b525df5-d0f8-483a-a5d3-1935c745590d.png)

**Comment by yigitcanustek** [comment]
Yeah. Finally make it! Thanks. 
The causing problem is 

`#!/usr/bin/env -S python3 -u`

with 

`~/.mozilla` path. 

I tried 

`/usr/lib...` 

path which is firstly specified in docs. I also created file before ops in 

`~/.mozilla`

too but i think i made typo errors.

Thanks again :)

**Comment by yigitcanustek** [comment]
> I am having the same issue but I am running MacOS Monterey 12.6. Mozilla Firefox version 108.0. There is no error, the extension is sending but no response from the application.

If you are able to solve your problem, i think we close this issue.
