### ISSUE TITLE
Create an example of getting select text to a variable

### ISSUE THREAD

**Issue by Hellboy00000** [mdn/webextensions-examples#516]
Proposal

I am trying for more than 3 weeks to get the selected text in Firefox. This is giving me anxiety.

I ask here but nobody answer.
https://stackoverflow.com/questions/75453918/firefox-extension-get-text-in-context-menu-javascript

Please create and example. There are many people asking this question.

**Comment by Rob--W** [comment]
Your attempt does not work because `window.getSelection()` in your case is called from the background page, where there is no selection. To retrieve the selection at the time of triggering the context menu, use `info.selectionText`, which is documented at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData#selectiontext

There is already an example of such usage at https://github.com/mdn/webextensions-examples/blob/main/menu-demo
