### ISSUE TITLE
zip does not contain a valid manifest

### ISSUE THREAD

**Issue by ianustec** [mdn/webextensions-examples#553]
### What information was incorrect, unhelpful, or incomplete?

Hi guys,

when i try to upload my extension, i receive the error "_[...]zip does not contain a valid manifest_" 

Please help me. On Chrome it work.

```
{
  "manifest_version": 3,
  "name": "XXX",
  "version": "1.6",
  "description": "xXXX",
  "permissions": [
    "storage"
  ],
  "host_permissions": [
    "https://example.com/*"
  ],
  "action": {},
  "background": {
    "service_worker": "background.js"
  },
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "content.js",
        "library/prism/prism.js"
      ],
      "css": [
        "styles.css"
      ],
      "run_at": "document_end",
      "all_frames": true
    }
  ],
  "icons": {
    "16": "images/icon16.png",
    "48": "images/icon48.png",
    "128": "images/icon128.png"
  },
  "web_accessible_resources": [
    {
      "resources": [
        "images/*"
      ],
      "matches": [
        "<all_urls>"
      ]
    },
    {
      "resources": [
        "styles.css"
      ],
      "matches": [
        "<all_urls>"
      ]
    }
  ]
}
```

### What did you expect to see?

extension loaded

**Comment by rebloor** [comment]
@ianustec I suspect it's because Firefox doesn't support `background.service_worker`. Check out https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background, which includes information on how to use scripts in Firefox and service workers in Chrome.
If you have any further questions, please post them to the [forum](https://discourse.mozilla.org/c/add-ons)
