### ISSUE TITLE
"can't read and change data on this site" testing applyCSS

### ISSUE THREAD

**Issue by dhowe** [mdn/webextensions-examples#556]
### What information was incorrect, unhelpful, or incomplete?

Extension loads but shows "can't read and change data on this site" for all sites in the addon menu

### What did you expect to see?

Expected the applyCss example to work

### Do you have anything more you want to share?

FF 124.0 (64-bit)
OSX 11.7.9

Below from visit to https://nytimes.com
![image](https://github.com/mdn/webextensions-examples/assets/737638/938ca4a6-34c3-4103-800f-3de78beb52c3)

**Comment by rebloor** [comment]
@dhowe This isn't unexpected. "Can't read and change data on this site", means that the extension doesn't have "host" (or site) permission, which would be needed to inject scripts into the site or manipulate requests to the server. 

If you locate the page action, you can see the extension works:
<img width="942" alt="image" src="https://github.com/mdn/webextensions-examples/assets/7352080/4480f8cc-51e5-4da2-9319-5f6eccb20174">

**Comment by dhowe** [comment]
ok then what needs to be added to make this example work ?

**Comment by rebloor** [comment]
If you look at the screenshot I added earlier the "page action" is the red circle icon in the address bar.

**Comment by dhowe** [comment]
Again, there is no page action, and no option to 'pin' the addon, bc it is disabled/grayed-out. Please re-open this ticket.

**Comment by rebloor** [comment]
@dhowe the two extensions are grayed in the add-ons list because they don't have a [browser action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Toolbar_button) and therefore no toolbar button to "pin".
In the example screenshot in your last message you can see that borderify is working because there is a red border around the mozilla.org page.
What you will find is that you cannot used borderify and apply-css together - remove borderify, reload the page and the click the red circle icon in the address bar. It will apply a wider red margin to the page. (And if you open the extension setting you can also find options to allow it to work in private pages and the restricted pages.)

**Comment by dhowe** [comment]
You're correct -- borderify seems to be working, though applyCss I still don't see any button in the address bar:

<img width="452" alt="image" src="https://github.com/mdn/webextensions-examples/assets/737638/55f605b4-74a3-429d-854a-f6e10ef988ea">

**Comment by rebloor** [comment]
@dhowe in dark mode it appears to be a white circle
<img width="1704" alt="image" src="https://github.com/mdn/webextensions-examples/assets/7352080/4b9a8a4d-424b-408d-9b77-ac7bf1ffbee2">

**Comment by dhowe** [comment]
Got it, thanks
